# Provides PASSWORD_KEEPER_SOURCES, PASSWORD_KEEPER_SOURCES_DIR variables

set(PASSWORD_KEEPER_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR})

set(PASSWORD_KEEPER_SOURCES
    ${PASSWORD_KEEPER_SOURCES}
    ${PASSWORD_KEEPER_SOURCES_DIR}/password.c
    ${PASSWORD_KEEPER_SOURCES_DIR}/password_keeper.c
    ${PASSWORD_KEEPER_SOURCES_DIR}/password_keeper_settings.c
    )
